### ISSUE TITLE
social features that allow users to share their achievements

### ISSUE THREAD

**Issue by AnandKrishnaShiju845** [Abhirajps/Task_manager#21]
As a user, I want social features **to share achievements**, workout summaries, and compete with friends for a more engaging experience.

**Comment by Abhirajps** [comment]
As a user, I want social features to share achievements, workout summaries, and compete with friends for a more engaging experience.

**Comment by Abhirajps** [comment]
implemented social features that allow users to share their achievements.

**Comment by AnandKrishnaShiju845** [comment]
implemented social features that allow users to share their achievements.
